version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  open-pull-requests-limit: 5
  ignore:
  # 忽略补丁版本更新，只更新次版本和主版本
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
